package com.example.noteapp.common

object Constants {
    const val ERROR_TAG_ADD_NOTE_SCREEN = "ERROR_TAG_ADD_NOTE_SCREEN"
    const val ERROR_TAG_HOME_SCREEN  = "ERROR_TAG_HOME_SCREEN"
    const val ERROR_TAG_DETAIL_SCREEN = "ERROR_TAG_DETAIL_SCREEN"

    const val STATUS_TAG_ADD_NOTE_SCREEN = "STATUS_TAG_ADD_NOTE_SCREEN"
    const val STATUS_TAG_HOME_SCREEN = "STATUS_TAG_HOME_SCREEN"
    const val STATUS_TAG_DETAIL_SCREEN = "STATUS_TAG_DETAIL_SCREEN"





    const val HOME_ROUTE = "HOME"
    const val ADD_NOTE_ROUTE = "ADD_NOTE"
    const val DETAIL_NOTE_ROUTE = "DETAIL_NOTE"
    const val SPlASH_ROUTE = "SPlASH_SCREEN"






}